inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'

Style/Documentation:
 Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
 Enabled: false
