language: generic
sudo: required

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop
  - docker-compose build
  - docker-compose run api bundle exec rails db:test:prepare

script:
  - docker-compose run api bundle exec rspec
  - docker-compose run api bundle exec rubocop --config .rubocop.yml
  - bundle exec rspec
